# Written by the Nothing shell: Settings, Interface, Idle.
# Edit it if you like, but the next change made there
# replaces the whole file.

general {
    lock_cmd = /home/nicolas/.config/quickshell/nothing/../../scripts/lock.sh
    before_sleep_cmd = loginctl lock-session
    inhibit_sleep = 3
}

listener {
    timeout = 120
    on-timeout = brightnessctl -s set 10%
    on-resume = brightnessctl -r
}

listener {
    timeout = 300
    on-timeout = loginctl lock-session
}

listener {
    timeout = 600
    on-timeout = hyprctl dispatch 'hl.dsp.dpms({ action = "disable" })'
    on-resume = hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })'
}

listener {
    timeout = 1200
    on-timeout = systemctl suspend || loginctl suspend
}

